# Generated by Django 4.2.1 on 2023-05-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='place',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='product.product'),
        ),
        migrations.AddField(
            model_name='place',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='product.product'),
        ),
        migrations.AddField(
            model_name='place',
            name='mechanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mech', to='product.product'),
        ),
        migrations.AddField(
            model_name='place',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='configurator.set'),
        ),
        migrations.AddField(
            model_name='orderset',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='orderset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.set'),
        ),
    ]
