# Generated by Django 4.0.5 on 2022-07-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_alter_place_additional_alter_place_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.product'),
        ),
    ]
