# Generated by Django 4.2.1 on 2023-05-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.country')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('article', models.CharField(max_length=255, unique=True)),
                ('ean', models.IntegerField(blank=True, null=True, unique=True)),
                ('price', models.FloatField(null=True)),
                ('price_currency', models.FloatField(null=True)),
                ('color', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='directory.color')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.component')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.currency')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturer')),
                ('series', models.ManyToManyField(to='catalogue.series')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.componenttype')),
            ],
        ),
    ]
