# Generated by Django 4.2.1 on 2023-05-20 17:49

import apps.core.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
        ('configurator', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.user.get_sentinel_user), related_name='clint_orders', to=settings.AUTH_USER_MODEL)),
                ('cover_color', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cover_colors', to='directory.color')),
                ('frame_color', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='frame_colors', to='directory.color')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_orders', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturer')),
                ('mech_color', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mech_colors', to='directory.color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.orderstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('place_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.placeset')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='place_sets',
            field=models.ManyToManyField(through='order.OrderSet', to='configurator.placeset'),
        ),
        migrations.AddField(
            model_name='order',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.series'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.orderstatus'),
        ),
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_from', to='directory.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_to', to='directory.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=15, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.city')),
            ],
        ),
    ]
