# Generated by Django 4.0.8 on 2022-11-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cover_color',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cover_colors', to='product.color'),
        ),
        migrations.AddField(
            model_name='order',
            name='frame_color',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='frame_colors', to='product.color'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
        ),
        migrations.AddField(
            model_name='order',
            name='mech_color',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mech_colors', to='product.color'),
        ),
        migrations.AddField(
            model_name='order',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.series'),
        ),
        migrations.AddField(
            model_name='order',
            name='sets',
            field=models.ManyToManyField(through='configurator.OrderSet', to='configurator.set'),
        ),
        migrations.AddField(
            model_name='currencyratehistory',
            name='from_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='currency_from', to='order.currency'),
        ),
        migrations.AddField(
            model_name='currencyratehistory',
            name='to_currency',
            field=models.ForeignKey(default='UAH', on_delete=django.db.models.deletion.PROTECT, related_name='currency_to', to='order.currency'),
        ),
    ]
